//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InsuranceEntities : DbContext
    {
        public InsuranceEntities()
            : base("name=InsuranceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CarMakeModel> tbl_CarMakeModel { get; set; }
        public virtual DbSet<tbl_Quotes> tbl_Quotes { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tlkp_CarMake> tlkp_CarMake { get; set; }
        public virtual DbSet<tlkp_CarModel> tlkp_CarModel { get; set; }
        public virtual DbSet<v_CarMakeModelMasterList> v_CarMakeModelMasterList { get; set; }
        public virtual DbSet<v_UserPremiums> v_UserPremiums { get; set; }
        public virtual DbSet<v_UserQuotes> v_UserQuotes { get; set; }
    
        public virtual ObjectResult<PROC_Car_Master_List_Result> PROC_Car_Master_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_Car_Master_List_Result>("PROC_Car_Master_List");
        }
    }
}
