//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CarMakeModelMasterList
    {
        public Nullable<int> Id { get; set; }
        public string Manufacturer { get; set; }
        public string Name { get; set; }
        public Nullable<int> MakeRisk { get; set; }
        public Nullable<int> ModelRisk { get; set; }
    }
}
